global: &global
  adapter: postgresql
  min_messages: warning
  encoding: unicode
  host: localhost

development:
  database: race_calendar_development
  <<: *global

test:
  database: race_calendar_test
  <<: *global

production:
  database: race_calendar_production
  <<: *global
